Repository wisemen-digital/vue-project-template, pull requests merged in 2024-09, with the labels that each got.

#79 [Feature] Add --cache to eslint
  .gitignore
  package.json
Labels: 📃 XS PR, ✨ feature

#78 [Feature] Update vue-core and refactor Date models
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/App.vue
  src/components/app/avatar/AppAvatar.vue
  src/components/app/link/AppTypedRouterLink.vue
  src/components/layout/AppPage.vue
  src/components/layout/sidebar/AppSidebar.vue
  src/components/layout/sidebar/AppSidebarFooter.vue
  src/components/layout/sidebar/AppSidebarMenu.vue
  src/components/layout/sidebar/AppSidebarMenuItem.vue
  src/components/layout/sidebar/AppSidebarMenuTooltipContent.vue
  src/composables/api-error-toast/apiErrorToast.composable.ts
  src/composables/document-title/documentTitle.composable.ts
  src/composables/loading/loading.composable.ts
  src/composables/refresh-prompt/refreshPrompt.composable.ts
  src/composables/router/typedRouteParams.composable.ts
  src/composables/router/typedRouteQuery.composable.ts
  src/composables/router/typedRouter.composable.ts
  src/icons/ClockIcon.vue
  src/libs/oAuth.lib.ts
  src/models/date/calendarDate.model.ts
  src/models/date/calendarDate.transformer.ts
  src/models/date/calendarDateDto.model.ts
  src/models/date/calendarDateTime.model.ts
  src/models/date/calendarDateTime.transformer.ts
  src/models/date/calendarTime.model.ts
  src/models/date/calendarTime.transformer.ts
  src/models/date/calendarTimeDto.model.ts
  src/models/time/time.model.ts
  src/models/time/time.transformer.ts
  src/models/time/timeDto.model.ts
  src/models/user/detail/userDto.builder.ts
  src/models/user/index/userIndexDto.builder.ts
  src/modules/auth/features/forgot-password/views/AuthForgotPasswordView.vue
  src/modules/auth/features/login/components/AuthLoginForm.vue
  src/modules/auth/features/login/views/AuthLoginView.vue
  src/modules/auth/features/reset-password/views/AuthResetPasswordView.vue
  src/modules/user/components/user-form/UserFormPersonalInfoSection.vue
  src/modules/user/features/create/components/UserCreateForm.vue
  src/modules/user/features/create/views/UserCreateView.vue
  src/modules/user/features/detail/views/UserDetailView.vue
  src/modules/user/features/detail/views/UserDetailViewDataProvider.vue
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/overview/views/UserOverviewView.vue
  src/modules/user/features/update/components/UserUpdateForm.vue
  src/modules/user/features/update/views/UserUpdateView.vue
  src/modules/user/features/update/views/UserUpdateViewDataProvider.vue
  src/utils/date.util.ts
  tests/user/userOverview.spec.ts
  tests/user/userUpdate.spec.ts
Labels: 📃 XL PR, ✨ feature

#81 IMPROVEMENT: changed the test files to the interceptor
  src/models/s3-file/s3FileCreate.model.ts
  tests/user/userCreate.spec.ts
  tests/user/userOverview.spec.ts
  tests/user/userUpdate.spec.ts
  tests/utils/interceptor.util.ts
  tests/utils/route.util.ts
Labels: 📃 S PR
