Repository wisemen-digital/vue-project-template, pull requests merged in 2024-04, with the labels that each got.

#30 [FEATURE] models
  src/models/currency/currency.transformer.ts
  src/models/date/date.transformer.ts
  src/models/date/dateTime.transformer.ts
  src/models/phone-number/phoneNumber.transformer.ts
Labels: 📃 XS PR, ✨ feature

#35 [Refactor] ENV variables
  changelog.md
  src/components/layout/sidebar/AppSidebarFooter.vue
  src/configs/zod.config.ts
  src/constants/environment.constant.ts
  src/libs/axios.lib.ts
  src/libs/http.lib.ts
  src/libs/oAuth.lib.ts
  src/main.ts
  src/models/date/date.model.ts
  src/modules/user/api/services/user.service.ts
  src/plugins/sentry/sentry.plugin.ts
  src/utils/currency/currency.util.spec.ts
  src/utils/currency/currency.util.ts
  src/utils/environment.util.ts
  src/utils/paginationParamsBuilder.util.ts
Labels: 📃 S PR

#33 [CHORE] improve changelog
  changelog.md
Labels: 📃 XS PR

#36 [Feature] Sentry errorHandler
  changelog.md
  package.json
  vite.config.ts
Labels: 📃 XS PR, ✨ feature

#37 Move form folder up
  src/components/form/AppForm.vue
  src/components/form/AppFormErrorBanner.vue
  src/components/form/AppFormGroup.vue
  src/components/form/AppFormSubmitButton.vue
  src/components/form/FormSection.vue
  src/modules/auth/components/AuthFormSubmitButton.vue
  src/modules/auth/features/forgot-password/components/AuthForgotPasswordForm.vue
  src/modules/auth/features/login/components/AuthLoginForm.vue
  src/modules/auth/features/reset-password/components/AuthResetPasswordForm.vue
  src/modules/user/components/user-form/UserFormName.vue
  src/modules/user/features/create/components/UserCreateForm.vue
  src/modules/user/features/update/components/UserUpdateForm.vue
Labels: 📃 XS PR

#38 [FEATURE] add s3File models
  src/models/s3-file/s3File.model.ts
  src/models/s3-file/s3File.transformer.ts
  src/models/s3-file/s3FileDto.model.ts
  src/models/s3-file/s3FileUuid.model.ts
Labels: 📃 XS PR, ✨ feature

#39 [IMPROVEMENT] phone number models
  src/models/phone-number/phoneNumber.transformer.ts
  src/models/phone-number/phoneNumberDto.model.ts
Labels: 📃 XS PR

#40 [IMPROVEMENT] add `FormLayout` component
  src/components/form/FormLayout.vue
  src/modules/user/features/create/components/UserCreateForm.vue
  src/modules/user/features/update/components/UserUpdateForm.vue
Labels: 📃 XS PR

#42 [IMPROVEMENT] computed route query and params
  src/composables/mutation/mutation.composable.ts
  src/composables/router/typedRouteParams.composable.ts
  src/composables/router/typedRouteQuery.composable.ts
  src/modules/user/api/queries/userDetail.query.ts
  src/types/query/queryKey.type.ts
Labels: 📃 XS PR

#43 [IMPROVEMENT] improve new item button
  src/components/app/AppNewItemButton.vue
Labels: 📃 XS PR

#47 [FIX] app layout
  src/components/layout/AppLayout.vue
Labels: 📃 XS PR, ✨ feature

#48 [IMPROVEMENT] `FormSubmitButton` and a few more small changes
  src/components/form/AppFormErrorBanner.vue
  src/components/form/FormGroup.vue
  src/components/form/FormSection.vue
  src/components/form/FormSubmitButton.vue
  src/modules/auth/components/AuthFormSubmitButton.vue
  src/modules/auth/features/forgot-password/components/AuthForgotPasswordForm.vue
  src/modules/auth/features/login/components/AuthLoginForm.vue
  src/modules/auth/features/reset-password/components/AuthResetPasswordForm.vue
  src/modules/user/features/create/components/UserCreateForm.vue
  src/modules/user/features/update/components/UserUpdateForm.vue
Labels: 📃 S PR

#41 [IMPROVEMENT] Overall improvements and fixes
  package.json
  pnpm-lock.yaml
  src/components/app/AppDivider.vue
  src/components/app/AppSearchInput.vue
  src/components/app/loader/AppPageLoader.vue
  src/composables/debounce-search/debounceSearch.composable.ts
  src/composables/error-toast/apiErrorToast.composable.ts
  src/composables/mutation/mutation.composable.ts
  src/composables/refresh-prompt/refreshPrompt.composable.ts
  src/composables/router/typedRouteParams.composable.ts
  src/composables/router/typedRouteQuery.composable.ts
  src/modules/auth/components/AuthLayout.vue
  src/modules/auth/features/forgot-password/views/AuthForgotPasswordView.vue
  src/modules/auth/features/reset-password/views/AuthResetPasswordView.vue
  src/modules/user/api/queries/userDetail.query.ts
  src/modules/user/features/create/views/UserCreateView.vue
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/overview/views/UserOverviewView.vue
  src/modules/user/features/update/views/UserUpdateView.vue
  src/types/query/queryKey.type.ts
Labels: 📃 S PR, ✨ feature

#45 [IMPROVEMENT] add keyboard shortcuts to sidebar
  package.json
  pnpm-lock.yaml
  src/components/layout/sidebar/AppSidebar.vue
  src/components/layout/sidebar/AppSidebarMenu.vue
  src/plugins/i18n/locales/en.json
  src/types/navigationItem.type.ts
Labels: 📃 XS PR

#44 [FEATURE] add dialog components + improve existing
  package.json
  pnpm-lock.yaml
  src/components/app/AppButtonGroup.vue
  src/components/app/dialog/AppDialogActionCancel.vue
  src/components/app/dialog/AppDialogActionPrimary.vue
  src/components/app/dialog/AppDialogActions.vue
  src/components/app/dialog/AppDialogContent.vue
  src/components/app/dialog/AppDialogHeader.vue
  src/components/dialogs/AppConfirmDialog.vue
  src/components/dialogs/AppDeactiveDialog.vue
  src/composables/unsaved-changes/unsavedChanges.composable.ts
  src/plugins/i18n/locales/en.json
  tailwind.config.ts
Labels: 📃 S PR, ✨ feature

#49 [IMPROVEMENT] keyboard shortcuts
  package.json
  pnpm-lock.yaml
  src/components/app/AppNewItemButton.vue
  src/components/app/AppSearchInput.vue
  src/components/app/dialog/AppDialogActionPrimary.vue
  src/components/form/FormSubmitButton.vue
  src/components/layout/AppLayout.vue
  src/components/layout/sidebar/AppSidebar.vue
  src/components/layout/sidebar/AppSidebarFooter.vue
  src/components/layout/sidebar/AppSidebarMenu.vue
  src/components/layout/sidebar/AppSidebarMenuItem.vue
  src/constants/keyboardShortcuts.constant.ts
  src/plugins/i18n/locales/en.json
  src/types/navigationItem.type.ts
Labels: 📃 M PR

#46 [CHORE] update changelog
  changelog.md
Labels: 📃 XS PR

#51 [IMPROVEMENT] computed table columns
  changelog.md
  src/modules/user/features/overview/components/UserOverviewTable.vue
Labels: 📃 XS PR
