Repository wisemen-digital/vue-project-template, pull requests merged in 2024-03, with the labels that each got.

#17 Remove duplicate uuid util
  src/utils/core/uuid/generateUuid.util.ts
Labels: 🛠️ refactor, 📃 XS PR

#22 Themes
  src/App.vue
  src/assets/styles/index.scss
  src/components/app/input/AppInput.vue
  src/components/layout/AppDarkModeToggle.vue
  src/components/layout/AppLayout.vue
  src/components/layout/ThemeProvider.vue
  src/composables/modal/modal.composable.ts
  src/composables/theme/theme.composable.spec.ts
  src/composables/theme/theme.composable.ts
  src/constants/theme.constant.ts
Labels: 📃 S PR, ✨ feature

#18 feat: add combox and select
  package.json
  src/components/app/combobox/AppCombobox.vue
  src/components/app/combobox/AppComboboxDivider.vue
  src/components/app/combobox/AppComboboxGroup.vue
  src/components/app/combobox/AppComboboxItem.vue
  src/components/app/select/AppSelect.vue
  src/components/app/select/AppSelectDivider.vue
  src/components/app/select/AppSelectGroup.vue
  src/components/app/select/AppSelectItem.vue
  src/components/app/select/AppSelectScrollDownButton.vue
  src/components/app/select/AppSelectScrollUpButton.vue
  src/components/app/table/AppTableBody.vue
  src/components/form/combobox/FormCombobox.vue
  src/components/form/group/FormGroup.vue
  src/components/form/select/FormSelect.vue
  src/utils/uuid/generateUuid.util.ts
Labels: 📃 L PR, ✨ feature

#26 [Feature] Latest fixes
  .dockerignore
  .github/CODEOWNERS
  .github/dependabot.yaml
  .github/workflows/auto-deploy-to-development.yml
  .github/workflows/promote-to-enviroment.yml
  .github/workflows/pullrequest-check.yaml
  .gitignore
  .husky/pre-commit
  Dockerfile
  index.html
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/assets/styles/index.scss
  src/components/app/combobox/AppCombobox.vue
  src/components/app/combobox/AppComboboxDivider.vue
  src/components/app/combobox/AppComboboxGroup.vue
  src/components/app/combobox/AppComboboxItem.vue
  src/components/app/input/AppInput.vue
  src/components/app/refresh-prompt/AppRefreshPrompt.vue
  src/components/app/select/AppSelect.vue
  src/components/app/select/AppSelectDivider.vue
  src/components/app/select/AppSelectGroup.vue
  src/components/app/select/AppSelectItem.vue
  src/components/app/select/AppSelectScrollDownButton.vue
  src/components/app/select/AppSelectScrollUpButton.vue
  src/components/app/table/AppTableBody.vue
  src/components/app/toast/AppToast.vue
  src/components/form/combobox/FormCombobox.vue
  src/components/form/group/FormGroup.vue
  src/components/form/input/FormInput.vue
  src/components/form/input/FormPasswordInput.vue
  src/components/form/select/FormSelect.vue
  src/modules/auth/features/forgot-password/components/AuthForgotPasswordForm.vue
  src/modules/auth/features/reset-password/components/AuthResetPasswordForm.vue
  src/types/datePicker.type.ts
  src/types/float.type.ts
  src/types/input.type.ts
  src/utils/currency/currency.util.spec.ts
  src/utils/uuid/generateUuid.util.ts
  vite.config.ts
Labels: 📃 XL PR, ✨ feature
