Repository wisemen-digital/vue-project-template, pull requests merged in 2024-07, with the labels that each got.

#69 [Feature] Time model
  src/models/date/calendarDateDto.model.ts
  src/models/time/time.model.ts
  src/models/time/time.transformer.ts
  src/models/time/timeDto.model.ts
Labels: 📃 XS PR, ✨ feature

#70 [Feature] Time
  src/models/date/calendarDateTime.transformer.ts
  src/models/time/time.model.ts
  src/models/user/detail/user.model.ts
  src/models/user/detail/userDto.model.ts
  src/models/user/user.transformer.ts
Labels: 📃 XS PR, ✨ feature

#73 Update packages
  package.json
  pnpm-lock.yaml
  src/composables/refresh-prompt/refreshPrompt.composable.ts
  src/libs/http.lib.ts
  src/modules/user/features/create/views/UserCreateView.vue
Labels: 📃 L PR, ✨ feature

#74 [Feature] Small improvements
  .gitignore
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/components/layout/sidebar/AppSidebar.vue
  src/icons/UsersIcon.vue
  src/icons/icons.ts
  src/models/time/time.model.ts
  src/models/user/detail/user.model.ts
  src/models/user/index/userIndex.model.ts
  src/models/user/index/userIndexDto.model.ts
  src/models/user/update/userUpdateForm.model.ts
  src/models/user/user.transformer.ts
  src/modules/user/components/user-form/UserFormPersonalInfoSection.vue
  src/modules/user/features/create/components/UserCreateForm.vue
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/update/components/UserUpdateForm.vue
  src/plugins/i18n/locales/en.json
  src/utils/date.util.ts
  src/utils/uuid.util.ts
  vite.config.ts
Labels: 📃 XL PR, ✨ feature
