Repository wisemen-digital/vue-project-template, pull requests merged in 2024-10, with the labels that each got.

#82 [FIX] - Deprecated sass js api
  vite.config.ts
Labels: 📃 XS PR

#83 [Chore] Update playwright
  .env.e2e
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/constants/testId.constant.ts
  src/models/s3-file/s3FileDto.model.ts
  src/stores/auth.store.ts
  tests/base.fixture.ts
  tests/user/userCreate.spec.ts
  tests/user/userOverview.spec.ts
  tests/user/userUpdate.spec.ts
  tests/utils/dateTimePicker.util.ts
  tests/utils/interceptor.util.ts
  tests/utils/selector.util.ts
Labels: 📃 M PR

#85 [Chore] Add PR template
  .github/pull_request_template.md
Labels: 📃 XS PR

#90 [Feature] routing props
  package.json
  pnpm-lock.yaml
  src/modules/user/api/queries/userDetail.query.ts
  src/modules/user/features/detail/views/UserDetailViewDataProvider.vue
  src/modules/user/features/update/views/UserUpdateViewDataProvider.vue
  src/modules/user/routes/user.routes.ts
  src/plugins/dayjs/dayjs.plugin.ts
  src/types/query/queryKey.type.ts
  src/types/reactivity.type.ts
  src/types/router/router.type.ts
Labels: 📃 XL PR, ✨ feature

#91 Update readme
  Dockerfile
  README.md
  openapi.config.ts
  src/client/index.ts
  src/client/services.gen.ts
  src/client/types.gen.ts
Labels: 📃 M PR

#92 Fix circular dependency which breaks HMR
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/libs/axios.lib.ts
  src/main.ts
  src/modules/auth/features/logout/views/AuthLogoutView.vue
  src/plugins/sentry/sentry.plugin.ts
  src/stores/auth.store.ts
  vite.config.ts
Labels: 🛠️ bugfix, 📃 XL PR
