Repository wisemen-digital/vue-project-template, pull requests merged in 2025-04, with the labels that each got.

#132 Refactor filters to pagination. Add code coverage for playwright.
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/app/search/AppPaginationSearchField.vue
  src/components/layout/sidebar/sidebar.context.ts
  src/models/user/index/userIndexFilters.model.ts
  src/models/user/index/userIndexFiltersDto.model.ts
  src/models/user/index/userIndexPagination.model.ts
  src/models/user/index/userIndexPaginationDto.model.ts
  src/models/user/user.transformer.ts
  src/modules/user/api/queries/userIndex.query.ts
  src/modules/user/api/services/user.service.ts
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/overview/views/UserOverviewView.vue
  src/types/queryKey.type.ts
  tests/base.fixture.ts
  vite.config.ts
Labels: 📃 XL PR

#138 Rename setting to settings
  src/components/layout/dashboard/AppDashboardLayout.vue
  src/components/layout/sidebar/AppSidebarUserProfile.vue
  src/mocks/handlers/user.mock.ts
  src/models/user/detail/userDetail.model.ts
  src/models/user/user.transformer.ts
  src/modules/settings/api/mutations/settingsRoleBulkUpdate.mutation.ts
  src/modules/settings/api/mutations/settingsRoleCreate.mutation.ts
  src/modules/settings/api/mutations/settingsRoleDelete.mutation.ts
  src/modules/settings/api/queries/settingsEventLogIndex.query.ts
  src/modules/settings/api/queries/settingsPermission.query.ts
  src/modules/settings/api/queries/settingsPreference.query.ts
  src/modules/settings/api/queries/settingsRole.query.ts
  src/modules/settings/api/services/settingsLog.service.ts
  src/modules/settings/api/services/settingsPermission.service.ts
  src/modules/settings/api/services/settingsPreference.service.ts
  src/modules/settings/api/services/settingsRole.service.ts
  src/modules/settings/components/SettingsDialogContainer.vue
  src/modules/settings/composables/settingsNavigation.composable.ts
  src/modules/settings/composables/settingsPreferences.composable.ts
  src/modules/settings/dialogs/SettingsDialog.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceFontSizeSection.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceHighContrastSection.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceInterfaceThemeSection.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceKeyboardShortcutSection.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceLanguageSection.vue
  src/modules/settings/features/appearance/components/SettingsAppearanceReduceMotionSection.vue
  src/modules/settings/features/appearance/views/SettingsAppearanceView.vue
  src/modules/settings/features/event-logs/components/SettingsEventLogIndexTable.vue
  src/modules/settings/features/event-logs/views/SettingsEventLogsView.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionRoleCreateDialog.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTable.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTableBody.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTableHeader.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTableHeaderCell.vue
  src/modules/settings/features/roles-and-permissions/views/SettingsRoleAndPermissionView.vue
  src/modules/settings/models/event-log/settingsEventLog.transformer.ts
  src/modules/settings/models/event-log/settingsEventLogIndex.model.ts
  src/modules/settings/models/event-log/settingsEventLogIndexDto.model.ts
  src/modules/settings/models/event-log/settingsEventLogIndexPagination.model.ts
  src/modules/settings/models/event-log/settingsEventLogIndexPaginationDto.model.ts
  src/modules/settings/models/permission/settingsPermission.model.ts
  src/modules/settings/models/permission/settingsPermission.transformer.ts
  src/modules/settings/models/preference/settingsPreference.model.ts
  src/modules/settings/models/preference/settingsPreference.transformer.ts
  src/modules/settings/models/preference/settingsPreferenceDto.builder.ts
  src/modules/settings/models/preference/settingsPreferenceDto.model.ts
  src/modules/settings/models/preference/settingsPreferenceTheme.enum.ts
  src/modules/settings/models/preference/settingsPreferenceUpdateDto.model.ts
  src/modules/settings/models/preference/settingsPreferenceUpdateForm.model.ts
  src/modules/settings/models/role/settingsRole.model.ts
  src/modules/settings/models/role/settingsRole.transformer.ts
  src/modules/settings/models/role/settingsRoleDto.model.ts
  src/modules/settings/models/role/settingsRolePermissionUpdateDto.model.ts
  src/modules/settings/models/role/settingsRolePermissionUpdateForm.model.ts
  src/modules/settings/models/role/settingsRoleUuid.model.ts
  src/modules/user/api/mutations/userUpdate.mutation.ts
  src/modules/user/api/services/user.service.ts
  src/modules/user/features/update/components/UserUpdateRoleForm.vue
  src/types/queryKey.type.ts
Labels: 📃 M PR, ✨ feature

#144 [Chore] Implement axe builder and fix a11y issue
  package.json
  pnpm-lock.yaml
  src/components/layout/sidebar/AppSidebarCollapseToggle.vue
  tests/base.fixture.ts
Labels: 📃 XS PR

#145 [FIX] - broken errors + contat address in detail
  src/constants/testId.constant.ts
  src/models/contact/create/contactCreateForm.model.ts
  src/modules/contact/features/detail/views/ContactDetailView.vue
  src/modules/contact/features/overview/components/ContactOverviewTable.vue
  src/modules/contact/features/overview/components/ContactOverviewTableAddressCell.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTable.vue
  src/modules/settings/features/roles-and-permissions/components/SettingsRoleAndPermissionTableBody.vue
  src/utils/address.util.ts
  src/utils/formango.util.ts
  tests/contact/contactOverview.spec.ts
Labels: 📃 XS PR

#143 [FEATURE]: autogen styles
  package.json
  pnpm-lock.yaml
  src/assets/styles/base.css
  src/assets/styles/colors.css
  src/assets/styles/tailwind.css
  src/assets/styles/themes/default.css
  src/assets/styles/themes/high-contrast.css
  src/components/decorative/BlobBackground.vue
  src/modules/settings/dialogs/SettingsDialog.vue
  src/themes/default.json
Labels: 📃 XL PR, ✨ feature

#147 Feat/global search without anim
  src/components/layout/header/AppHeaderCommandMenuDialog.vue
  src/components/layout/header/AppHeaderCommandMenuRecentResultsLabel.vue
  src/components/layout/header/AppHeaderCommandMenuSearchField.vue
  src/components/layout/header/AppHeaderCommandMenuTrigger.vue
Labels: 📃 S PR

#139 feat(global search) add global search to template
  package.json
  pnpm-lock.yaml
  src/api/global-search/queries/globalSearchIndex.query.ts
  src/api/global-search/services/globalSearch.service.ts
  src/assets/styles/themes/default.css
  src/client/sdk.gen.ts
  src/components/layout/AppPage.vue
  src/components/layout/dashboard/AppDashboardLayoutClassic.vue
  src/components/layout/dashboard/AppDashboardLayoutFloating.vue
  src/components/layout/header/AppCommandMenuShortcut.vue
  src/components/layout/header/AppHeader.vue
  src/components/layout/header/AppHeaderCommandMenu.vue
  src/components/layout/header/AppHeaderCommandMenuDialog.vue
  src/components/layout/header/AppHeaderCommandMenuRecentResultsLabel.vue
  src/components/layout/header/AppHeaderCommandMenuSearchField.vue
  src/components/layout/header/AppHeaderCommandMenuTrigger.vue
  src/components/layout/header/commandAction.composable.ts
  src/components/layout/header/commandMenu.composable.ts
  src/components/layout/header/commandMenuAction.type.ts
  src/icons/EnterKeyIcon.vue
  src/icons/EscKeyIcon.vue
  src/icons/icons.ts
  src/locales/en-US.json
  src/locales/nl-BE.json
  src/models/global-search/globalSearch.transformer.ts
  src/models/global-search/globalSearchIndex.model.ts
  src/models/global-search/globalSearchIndexDto.model.ts
  src/types/queryKey.type.ts
Labels: 📃 XL PR

#146 Feat/settings jobs
  src/client/sdk.gen.ts
  src/client/types.gen.ts
  src/client/zod.gen.ts
  src/components/layout/dashboard/AppDashboardLayout.vue
  src/icons/CopyIcon.vue
  src/icons/UserSquareIcon.vue
  src/icons/UsersIcon.vue
  src/icons/icons.ts
  src/locales/en-US.json
  src/locales/nl-BE.json
  src/modules/settings/api/queries/settingsJobsIndex.query.ts
  src/modules/settings/api/services/settingsJob.service.ts
  src/modules/settings/dialogs/SettingsDialog.vue
  src/modules/settings/features/event-logs/components/SettingsEventLogIndexTableContentCell.vue
  src/modules/settings/features/jobs/components/SettingsJobIndexTable.vue
  src/modules/settings/features/jobs/components/SettingsJobIndexTableContentCell.vue
  src/modules/settings/features/jobs/views/SettingsJobView.vue
  src/modules/settings/models/jobs/settingsJob.transformer.ts
  src/modules/settings/models/jobs/settingsJobIndex.model.ts
  src/modules/settings/models/jobs/settingsJobIndexDto.model.ts
  src/modules/settings/models/jobs/settingsJobIndexPagination.model.ts
  src/modules/settings/models/jobs/settingsJobIndexPaginationDto.model.ts
  src/modules/settings/types/settingsMenuItemKey.type.ts
  src/types/queryKey.type.ts
Labels: 📃 L PR
