Repository wisemen-digital/vue-project-template, pull requests merged in 2025-02, with the labels that each got.

#114 Add serializer for query. Cleanup layout.
  src/components/layout/dashboard/AppDashboardLayout.vue
  src/components/layout/sidebar/AppSidebar.vue
  src/libs/http.lib.ts
  src/models/user/user.transformer.ts
  src/modules/user/api/services/user.service.ts
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/overview/views/UserOverviewView.vue
  src/utils/object.util.ts
Labels: 📃 XS PR, ✨ feature

#116 [FIX] - Remove partial from pagination params type
  src/utils/paginationDtoBuilder.util.ts
Labels: 📃 XS PR

#117 Update packages and fix auth header logic
  package.json
  pnpm-lock.yaml
  src/libs/http.lib.ts
Labels: 🛠️ bugfix, 📃 L PR

#118 Update auth package
  package.json
  pnpm-lock.yaml
  tests/.auth/user.json
Labels: 🛠️ bugfix, 📃 XS PR

#120 Update backend endpoint
  README.md
  openapi.config.ts
  src/client/client.gen.ts
  src/client/sdk.gen.ts
  src/client/types.gen.ts
  src/client/zod.gen.ts
  src/middlewares/auth.middleware.ts
Labels: 📃 S PR, ✨ feature

#121 Add ApiError model and utils
  openapi.config.ts
  package.json
  pnpm-lock.yaml
  src/components/app/AppSearchInputField.vue
  src/components/app/error-state/AppErrorState.vue
  src/components/layout/dashboard/AppDashboardLayout.vue
  src/components/layout/sidebar/AppSidebarCollapseToggle.vue
  src/components/layout/sidebar/AppSidebarUserProfile.vue
  src/composables/api-error-toast/apiErrorToast.composable.ts
  src/composables/language/language.composable.ts
  src/composables/unsaved-changes/unsavedChanges.composable.ts
  src/configs/zod.config.ts
  src/locales/en-US.json
  src/locales/nl-BE.json
  src/middlewares/auth.middleware.ts
  src/models/api-error/apiError.model.ts
  src/modules/auth/features/login/views/AuthLoginView.vue
  src/modules/settings/api/services/settingRole.service.ts
  src/modules/settings/features/application/components/font-size/SettingApplicationOverviewFontSize.vue
  src/modules/settings/features/application/components/high-contrast/SettingApplicationOverviewHighContrast.vue
  src/modules/settings/features/application/components/interface-theme/SettingApplicationOverviewInterfaceTheme.vue
  src/modules/settings/features/application/components/keyboard-shortcuts/SettingApplicationOverviewKeyboardShortcut.vue
  src/modules/settings/features/application/components/language/SettingApplicationOverviewLanguage.vue
  src/modules/settings/features/application/components/reduce-motion/SettingApplicationOverviewReduceMotion.vue
  src/modules/settings/features/roles-and-permissions/components/SettingRoleAndPermissionRoleCreateDialog.vue
  src/modules/settings/features/roles-and-permissions/components/SettingRoleAndPermissionTableBody.vue
  src/modules/settings/features/roles-and-permissions/components/SettingRoleAndPermissionTableHeader.vue
  src/modules/settings/features/roles-and-permissions/components/SettingRoleAndPermissionTableHeaderCell.vue
  src/modules/settings/views/SettingView.vue
  src/modules/user/components/user-form/UserFormNameSection.vue
  src/modules/user/features/detail/views/UserDetailView.vue
  src/modules/user/features/overview/components/UserOverviewTable.vue
  src/modules/user/features/overview/views/UserOverviewView.vue
  src/modules/user/features/update/components/UserUpdateRoleForm.vue
  src/modules/user/features/update/views/UserUpdateView.vue
  src/types/apiError.type.ts
  tests/base.fixture.ts
Labels: 📃 M PR, ✨ feature

#122 [Feature] Add permissions
  src/models/user/detail/user.model.ts
  src/models/user/user.transformer.ts
  src/modules/user/features/detail/views/UserDetailView.vue
  src/stores/auth.store.ts
Labels: 📃 XS PR, ✨ feature
